In [ ]:
print(__doc__)

from sklearn_theano.datasets import fetch_asirra
from sklearn_theano.feature_extraction import OverfeatTransformer
from sklearn_theano.utils import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.metrics import classification_report, accuracy_score
import matplotlib.pyplot as plt
import time

asirra = fetch_asirra(image_count=20)
X = asirra.images.astype('float32')
y = asirra.target
X_train, X_test, y_train, y_test = train_test_split(
    X, y, train_size=.6, random_state=1999)
tf = OverfeatTransformer(output_layers=[-3])
clf = LogisticRegression()
pipe = make_pipeline(tf, clf)
t0 = time.time()
pipe.fit(X_train, y_train)
print("Total transform time")
print("====================")
print(time.time() - t0)
print()
y_pred = pipe.predict(X_test)
print(classification_report(y_test, y_pred))
print()
print("Accuracy score")
print("==============")
print(accuracy_score(y_test, y_pred))
f, axarr = plt.subplots(1, 2)
axarr[0].imshow(asirra.images[asirra.target == 0][-1])
axarr[0].axis('off')
axarr[1].imshow(asirra.images[asirra.target == 1][0])
axarr[1].axis('off')
plt.show()

Automatically created module for IPython interactive environment


//anaconda/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")


Downloading: /Users/apple/sklearn_theano_data/asirra/petimages.tar Bytes: 100


In [38]:
import cv2
from sklearn_theano.feature_extraction import OverfeatTransformer
test=cv2.imread('example2.jpg')

print test.shape
tf = OverfeatTransformer(output_layers=[-2])
features=tf.transform(test)
print features

(256, 256, 3)
[[ 0.  0.  0. ...,  0.  0.  0.]]


In [6]:
import numpy as np
print np.mean(features)

0.123066


In [41]:
print features[0]

[ 0.  0.  0. ...,  0.  0.  0.]


In [42]:
import numpy as np
x=[[1,2,3,7,8],[4,5,6,0,1],[2,3,4,3,3],[6,8,1,9,1]]
x=np.array(x)
x=x.astype(np.float64)
print x

[[ 1.  2.  3.  7.  8.]
 [ 4.  5.  6.  0.  1.]
 [ 2.  3.  4.  3.  3.]
 [ 6.  8.  1.  9.  1.]]


In [ ]:
import mdp
pcaNode=mdp.nodes.PCANode(output_dim=4,svd=True)
y=pcaNode.execute(np.zeros(shape=(3000,20000)))

In [48]:
print y

[[  1.02736841e+00  -6.15899905e+00  -4.45808086e-01   1.48492330e-15]
 [ -4.77127714e+00   3.39866341e+00  -6.09509186e-01  -6.93889390e-17]
 [ -2.37607234e+00  -6.65052814e-01   1.04856330e+00  -1.24900090e-16]
 [  6.11998107e+00   3.42538845e+00   6.75396823e-03  -1.34614542e-15]]


In [2]:
print x.mean(axis=0)

[ 3.25  4.5   3.5   4.75  3.25]


In [36]:
def myPCA(data, dims_rescaled_data=2):
    """
    returns: data transformed in 2 dims/columns + regenerated original data
    pass in: data as 2D NumPy array
    """
    import numpy as NP
    from scipy import linalg as LA
    n, p = data.shape
    # mean center the data
    data -= data.mean(axis=0)
    # calculate the covariance matrix
    R = NP.dot(data, data.T)
    # calculate eigenvectors & eigenvalues of the covariance matrix
    # use 'eigh' rather than 'eig' since R is symmetric, 
    # the performance gain is substantial
    evals, evecs = LA.eigh(R)
    # sort eigenvalue in decreasing order
    idx = NP.argsort(evals)[::-1]
    evecs = evecs[:,idx]
    # sort eigenvectors according to same index
    evals = evals[idx]
    # select the first n eigenvectors (n is desired dimension
    # of rescaled data array, or dims_rescaled_data)
    evecs = evecs[:, :dims_rescaled_data]
    real_evecs=NP.zeros(shape=(p,dims_rescaled_data))
    for i in range(dims_rescaled_data):
        real_evecs[:,i]=NP.dot(data.T, NP.array([evecs[:,i]]).T)[:,0]
    # carry out the transformation on the data using eigenvectors
    # and return the re-scaled data, eigenvalues, and eigenvectors
    return NP.dot(real_evecs.T, data.T).T, evals, real_evecs


newdata , eigenvalues , eigenvectors = myPCA(x,2)

In [13]:
print eigenvectors

[[ 0.20785873 -0.43233834 -0.4468827 ]
 [ 0.2993103  -0.4878914  -0.44283787]
 [-0.43230226 -0.04346693 -0.47519653]
 [ 0.82401095  0.23158791  0.0513955 ]
 [ 0.03645274  0.72077959 -0.6129741 ]]


In [38]:
print eigenvalues

[  6.69204595e+01   6.16597636e+01   1.66977691e+00   2.84217094e-14]


In [39]:
print newdata

[[ -8.40437966  48.36275859]
 [ 39.03139744 -26.68757322]
 [ 19.43744222   5.22224284]
 [-50.06446    -26.8974282 ]]
